---
title: "Naive  bayes"
---

```{r}
install.packages('el071')
library(e1071)
```
Dados de Créditos de Banco Alemão
```{r}
credito = read.csv("C:\\Users\\nelzi\\OneDrive\\Área de Trabalho\\R\\Credit.csv")
head(credito)
dim(credito)
```

Transformamos a classe em fator

```{r}
credito$class = as.factor(credito$class)
```


Separamos dados de treino e teste
```{r}
amostra = sample(2,1000,replace = T, prob = c(0.7,0.3))
amostra
creditotreino = credito[amostra==1,]
creditoteste = credito[amostra==2,]
```
Dimensões dos conjuntos
```{r}
dim(creditotreino)
dim(creditoteste)
```
Criamos o modelo 
```{r}
modelo <- naiveBayes(class ~., creditotreino)
modelo
```

predicao
```{r}
predicao <- predict(modelo, creditoteste)
predicao
```

Matriz de confusão 
```{r}
confusao = table(creditoteste$class,predicao)
taxaacerto = (confusao[1] + confusao[4])/sum(confusao)
taxaerro = (confusao[2] + confusao[3]) /sum(confusao)
taxaacerto
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
